version: "3.7"
services:
  counter:
    build: .
    ports:
      - ${PORT:-80}:80
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
